### ISSUE TITLE
Important: Addtrack check

### ISSUE THREAD

**Issue by blerude** [ckelley324/bwa-u3-jammming-prj#1]
https://github.com/ckelley324/bwa-u3-jammming-prj/blob/master/src/Components/App/App.js#L22-L24

You want to make sure that the track isn't already in the playlist before adding it. Use the built-in JS function 'find'.

**Comment by ckelley324** [comment]
I must have missed that step in the project. I’ll add a condition that will include a .find for the track id. Thanks!

**Comment by ckelley324** [comment]
Added the condition with .find as suggested.
