### ISSUE TITLE
Subtle: Alignment

### ISSUE THREAD

**Issue by blerude** [ckelley324/bwa-u3-jammming-prj#3]
https://github.com/ckelley324/bwa-u3-jammming-prj/blob/master/src/Components/App/App.js#L51-L60

Don't abandon your alignment practices in your JSX. You still want the contents of the main container div to be indented further inside, and the elements of the className='App' div to be indented inside that as well.

**Comment by ckelley324** [comment]
Duly noted! I’ll make sure the indentations look neat.
